# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://zhuchuanliang.github.io
date_format: "ordinal"
title: 那一抹天空蓝
subtitle: "越努力，越幸运"
description: "朱传亮的个人博客"
keywords: 码志, Zhuang Ma, mzlogin, mazhuang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zhuchuanliang
organization: cpupt
organization_url: http://www.cqupt.edu.cn
github_username: zhuchuanliang
location: Wuhan, China
email: chuanliangzhu@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhuchuanliang/zhuchuanliang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhuchuanliang
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhuchuanliang
    repo: 博客评论
    oauth:
        client_id: c65d2442ebad2413739d
        client_secret: 1dd421be33ea6e94509867044604ae0276fe683d
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhuchuanliang
    repo: 博客评论
    clientID: e57db18bee8d1a963bc3
    clientSecret: 9a2b13fe513785e403a85f7bab002451c5b6e606
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
