# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://zhuchuanliang.github.io
date_format: "ordinal"
title: 那一抹天空蓝
subtitle: "越努力，越幸运"
description: "朱传亮的个人博客"
keywords: 那一抹天空蓝, zhuchuanliang, zhuchuanliang, zhuchuanliang
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zhuchuanliang
organization: cqupt
organization_url: http://www.cqupt.edu.cn
github_username: zhuchuanliang
location: Chongqing, China
email: chuanliangzhu@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Type

  -
    href: /wiki/
    label: Demo

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zhuchuanliang.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitment
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhuchuanliang
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhuchuanliang
    repo: zhuchuanliang.github.io
    oauth:
        client_id: 62f316a4225067066a98
        client_secret: fc884e60b1852766b6716d454b69792cdd0817d9
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhuchuanliang
    repo: zhuchuanliang.github.io
    clientID: e57db18bee8d1a963bc3
    clientSecret: 9a2b13fe513785e403a85f7bab002451c5b6e606
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
